ScreenManager:
    LoginScreen:
    RegisterScreen:
    FormulirScreen:

<LoginScreen>:
    name: "login"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Login"
            font_size: 24

        TextInput:
            id: username
            hint_text: "Username"
            multiline: False
            write_tab: False

        TextInput:
            id: password
            hint_text: "Password"
            password: True
            multiline: False
            write_tab: False

        Button:
            text: "Login"
            on_press: root.login_user()

        Button:
            text: "Register"
            on_press: 
                root.manager.current = "register"
                root.manager.get_screen('register').reset_fields()

<RegisterScreen>:
    name: "register"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Register"
            font_size: 24

        TextInput:
            id: username
            hint_text: "Username"
            multiline: False
            write_tab: False

        TextInput:
            id: email
            hint_text: "Email"
            multiline: False
            write_tab: False

        TextInput:
            id: password
            hint_text: "Password"
            password: True
            multiline: False
            write_tab: False

        TextInput:
            id: confirm_password
            hint_text: "Confirm Password"
            password: True
            multiline: False
            write_tab: False

        Button:
            text: "Register"
            on_press: root.register_user()

        Button:
            text: "Back to Login"
            on_press: 
                root.manager.current = "login"
                root.manager.get_screen('login').reset_fields()

<FormulirScreen>:
    name: "form"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Formulir Permohonan"
            font_size: 24
            size_hint_y: None
            height: 50
        Spinner:
            id: permohonan
            text: "Pilih Jenis Permohonan"
            values: ["Legalitas Perusahaan", "Jasa NIB & OSS", "Merek dan Hak Cipta", "Perpajakan"]
            on_text: root.update_layanan(self.text)
        Spinner:
            id: layanan
            text: "Pilih Produk Layanan"

        TextInput:
            id: nama
            hint_text: "Masukkan Nama"
            write_tab: False
        
        TextInput:
            id: nik
            hint_text: "Masukkan No. KTP"
            multiline: False
            write_tab: False

        TextInput:
            id: no_hp
            hint_text: "Masukkan No. HP"
            multiline: False
            write_tab: False

        TextInput:
            id: email
            hint_text: "Masukkan Email"
            multiline: False
            write_tab: False
        
        BoxLayout:
            orientation: "horizontal"
            Button:
                id: file1
                text: "Pilih File 1"
                on_release: root.upload_file_1()
            Button:
                id: file2
                text: "Pilih File 2"
                on_release: root.upload_file_2()
        Button:
            text: "Pratinjau"
            on_release: root.preview_data()
        Button:
            text: "Submit"
            on_release: root.submit_data()

        Button:
            text: "Logout"
            on_press: 
                app.root.current = "login"
                root.manager.get_screen('login').reset_fields()
            