<LoginScreen>:
    orientation: "vertical"
    TextInput:
        id: username
        hint_text: "Username"
    TextInput:
        id: password
        hint_text: "Password"
        password: True
    Button:
        text: "Login"
        on_press: root.login()
    Button:
        text: "Register"
        on_press: root.register()

<RegisterScreen>:
    orientation: "vertical"
    TextInput:
        id: username
        hint_text: "Username"
    TextInput:
        id: password
        hint_text: "Password"
        password: True
    TextInput:
        id: email
        hint_text: "Email"
    Button:
        text: "Register"
        on_press: root.register_user()
