name: Sync Folder C

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari pada tengah malam
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo2
        uses: actions/checkout@v2
        with:
          persist-credentials: false # tidak menggunakan kredensial dari repo2

      - name: Checkout repo1
        uses: actions/checkout@v2
        with:
          repository: user/repo1
          token: ${{ secrets.REPO1_PAT }} # Personal Access Token untuk repo1
          path: repo1

      - name: Sync folder c
        run: |
          rm -rf path/to/c
          cp -r repo1/path/to/c path/to/c
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add path/to/c
          git commit -m "Update folder c from repo1"
          git push origin main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
